nome = input('Digite seu nome')
print('Olá' , '{}!'.format(nome) , 'prazer em conhece-lo!')
idade = input('qual é a sua idade?')
print('ta velho hein??')
peso = input('qual é o seu peso?')
print('vish vamos cuidar ne?')
print(nome, idade, peso)
print('Olá mundo')
